# Generated by Django 2.2.9 on 2021-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='PM49L7S9LD', max_length=10, null=True, verbose_name='confirmation code'),
        ),
    ]
