# Generated by Django 3.0.5 on 2021-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210326_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='AQ02GJ9WFZEJT83F7OZOSOUD0G2C85', max_length=30, null=True, verbose_name='confirmation code'),
        ),
    ]
