# Generated by Django 3.0.5 on 2021-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210330_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='OF4WM8P549', max_length=10, null=True, verbose_name='confirmation code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Пользователь')], default='user', max_length=50, verbose_name='role'),
        ),
    ]
