# Generated by Django 3.0.5 on 2021-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210330_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='PENJNTT2J9', max_length=10, null=True, verbose_name='confirmation code'),
        ),
    ]
