# Generated by Django 3.0.5 on 2021-03-30 17:06

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210330_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, validators=[api.models.Title.my_year_validator], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ZR2PFGHV8J', max_length=10, null=True, verbose_name='confirmation code'),
        ),
    ]
