# Generated by Django 3.0.5 on 2021-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210330_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='96e432f1-fde7-47ff-ba35-c834f4fcca72', max_length=100, null=True, verbose_name='confirmation code'),
        ),
    ]
