# Generated by Django 3.0.5 on 2021-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210326_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='AWEHANQSIXG3RO8VL0NNVH3OMCM494', max_length=30, null=True, verbose_name='confirmation code'),
        ),
    ]
