# Generated by Django 3.0.5 on 2021-03-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210331_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pub_date',), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='7b48afcc-154f-4944-9f21-7e6efbce14ee', max_length=100, null=True, verbose_name='confirmation code'),
        ),
    ]
