NAME_MAX_LENGTH = 100
ROLE_MAX_LENGTH = 50
BIO_MAX_LENGTH = 1000
TEXT_MAX_LENGTH = 2000
SLUG_MAX_LENGTH = 100
EMAIL_MAX_LENGTH = 255
TITLE_NAME_MAX_LENGTH = 200

YEAR_MAX_DIGITS = 4
YEAR_DECIMAL_PLACES = 0

SCORE_DEFAULT = 1
SCORE_MIN_VALUE = 1
SCORE_MAX_VALUE = 10

FIRST_NAME_VERBOSE_NAME = 'first name'
LAST_NAME_VERBOSE_NAME = 'last name'
USERNAME_VERBOSE_NAME = 'username'
AUTHOR_VERBOSE_NAME = 'author'
REVIEW_VERBOSE_NAME = 'review'
SCORE_VERBOSE_NAME = 'score'
BIO_VERBOSE_NAME = 'bio'
EMAIL_VERBOSE_NAME = 'email address'
ROLE_VERBOSE_NAME = 'role'
CATEGORY_NAME_VERBOSE_NAME = 'category'
GENRE_VERBOSE_NAME = 'genre'
TILE_VERBOSE_NAME = 'title'
DESCRIPTION_VERBOSE_NAME = 'description'
YEAR_VERBOSE_NAME = 'year'
PUB_DATE_VERBOSE_NAME = 'pub date'
COMMENT_VERBOSE_NAME = 'comment'

TITLE_RELATED_NAME = 'titles'
REVIEW_RELATED_NAME = 'reviews'
COMMENT_RELATED_NAME = 'comments'
